#!/usr/bin/env bash
# Config a Ubuntu server to:
# localhost resolves to 127.0.0.2
# facebook resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
